---
- hosts: localhost
  tasks:
    #- include_vars: inventories/poc/group_vars/all/vault
    - name: debug
      debug: var=vault_private_key
    - name: Ensure ssh directory exists.
      file: 
        dest: "{{ key_file | dirname }}"
        mode: 0700 
        state: directory
        owner: "{{ local_user }}"
    
    - name: Install ssh key
      copy: 
        content: "{{ vault_private_key }}" 
        dest: "{{ key_file }}"
        mode: 0600
        owner: "{{ local_user }}"
